%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\Toby\Dropbox\Tobys_Stuff\Phd\Writing\OneHectarePlot - working.xlsx
%    Worksheet: Full Census
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2018/07/27 09:51:04

%% Import the data, extracting spreadsheet dates in Excel serial date format
[~, ~, raw, dates] = xlsread('C:\Users\Toby\Dropbox\Tobys_Stuff\Phd\Writing\OneHectarePlot - working.xlsx','Full Census','A2:W20489','',@convertSpreadsheetExcelDates);
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
stringVectors = string(raw(:,[3,4,16,18,19,20,21]));
stringVectors(ismissing(stringVectors)) = '';
raw = raw(:,[1,2,5,6,7,8,9,10,11,12,13,14,15,22,23]);
dates = dates(:,17);

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),dates); % Find non-numeric cells
dates(R) = {NaN}; % Replace non-numeric Excel dates with NaN

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Create table
FullCensus = table;

%% Allocate imported array to column variable names
FullCensus.tag = data(:,1);
FullCensus.stemtag = data(:,2);
FullCensus.stemtag2 = categorical(stringVectors(:,1));
FullCensus.spcode = categorical(stringVectors(:,2));
FullCensus.SPECIES = data(:,3);
FullCensus.plotnum = data(:,4);
FullCensus.subplot = data(:,5);
FullCensus.lx = data(:,6);
FullCensus.ly = data(:,7);
FullCensus.dbh08inmm = data(:,8);
FullCensus.dbh10inmm = data(:,9);
FullCensus.hom10 = data(:,10);
FullCensus.dbh16mm = data(:,11);
FullCensus.hom16 = data(:,12);
FullCensus.Growth_Rate = data(:,13);
FullCensus.notes16 = stringVectors(:,3);
FullCensus.date = datetime([dates{:,1}].', 'ConvertFrom', 'Excel');
FullCensus.codes16 = categorical(stringVectors(:,4));
FullCensus.codes10 = categorical(stringVectors(:,5));
FullCensus.notes2008census = stringVectors(:,6);
FullCensus.notes1 = stringVectors(:,7);
FullCensus.lxold = data(:,14);
FullCensus.lyold = data(:,15);

% For code requiring serial dates (datenum) instead of datetime, uncomment
% the following line(s) below to return the imported dates as datenum(s).

% FullCensus.date=datenum(FullCensus.date);

%% Clear temporary variables
clearvars data raw dates stringVectors R;