%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\Toby\Dropbox\Tobys_Stuff\Phd\Writing\OneHectarePlot - working.xlsx
%    Worksheet: Everything_v2
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2018/04/06 14:12:14

%% Import the data
[~, ~, raw0_0] = xlsread('C:\Users\Toby\Dropbox\Tobys_Stuff\Phd\Writing\OneHectarePlot - working.xlsx','Everything_v2','A2:AG484');
[~, ~, raw0_1] = xlsread('C:\Users\Toby\Dropbox\Tobys_Stuff\Phd\Writing\OneHectarePlot - working.xlsx','Everything_v2','AI2:AI484');
[~, ~, raw0_2] = xlsread('C:\Users\Toby\Dropbox\Tobys_Stuff\Phd\Writing\OneHectarePlot - working.xlsx','Everything_v2','AL2:AL484');
raw = [raw0_0,raw0_1,raw0_2];
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
stringVectors = string(raw(:,[1,10,11,12,21,22,34,35]));
stringVectors(ismissing(stringVectors)) = '';
raw = raw(:,[2,3,4,5,6,7,8,9,13,14,15,16,17,18,19,20,23,24,25,26,27,28,29,30,31,32,33]);

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Create table
OneHa_v2 = table;

%% Allocate imported array to column variable names
OneHa_v2.Tree_ID = stringVectors(:,1);
OneHa_v2.x = data(:,1);
OneHa_v2.y = data(:,2);
OneHa_v2.Volume_m3 = data(:,3);
OneHa_v2.Branch_Length_m = data(:,4);
OneHa_v2.Height_m = data(:,5);
OneHa_v2.DBH_cm = data(:,6);
OneHa_v2.DBH_triangulation_cm = data(:,7);
OneHa_v2.censusID = data(:,8);
OneHa_v2.Dead = categorical(stringVectors(:,2));
OneHa_v2.species = (stringVectors(:,3));
OneHa_v2.code = stringVectors(:,4);
OneHa_v2.in3 = data(:,9);
OneHa_v2.Density = data(:,10);
OneHa_v2.Elasticity = data(:,11);
OneHa_v2.MOR = data(:,12);
OneHa_v2.VarName17 = data(:,13);
OneHa_v2.VarName18 = data(:,14);
OneHa_v2.tag = data(:,15);
OneHa_v2.stemtag = data(:,16);
OneHa_v2.stemtag2 = categorical(stringVectors(:,5));
OneHa_v2.spcode = categorical(stringVectors(:,6));
OneHa_v2.SPECIES = data(:,17);
OneHa_v2.plotnum = data(:,18);
OneHa_v2.subplot = data(:,19);
OneHa_v2.lx = data(:,20);
OneHa_v2.ly = data(:,21);
OneHa_v2.dbh08inmm = data(:,22);
OneHa_v2.dbh10inmm = data(:,23);
OneHa_v2.hom10 = data(:,24);
OneHa_v2.dbh16mm = data(:,25);
OneHa_v2.hom16 = data(:,26);
OneHa_v2.Growth_Rate = data(:,27);
OneHa_v2.TLS_ID_v2 = stringVectors(:,7);
OneHa_v2.TLS_ID_v1 = stringVectors(:,8);

%% Clear temporary variables
clearvars data raw raw0_0 raw0_1 raw0_2 stringVectors R;

% ========================================
%%            FIELD DATA IMPORT BELOW 
% =======================================
%% Import the data
[~, ~, raw] = xlsread('C:\Users\Toby\Dropbox\Tobys_Stuff\Phd\Writing\OneHectarePlot - working.xlsx','Everything_v2','A487:X507');
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
stringVectors = string(raw(:,[2,3,8,10,11,12,21,22]));
stringVectors(ismissing(stringVectors)) = '';
raw = raw(:,[1,4,5,6,7,9,13,14,15,16,17,18,19,20,23,24]);

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Create table
Field21 = table;

%% Allocate imported array to column variable names
Field21.CensusID = data(:,1);
Field21.VarName2 = stringVectors(:,1);
Field21.Quality = stringVectors(:,2);
Field21.Height_m = data(:,2);
Field21.dbh08 = data(:,3);
Field21.dbh10 = data(:,4);
Field21.dbh16 = data(:,5);
Field21.Species = stringVectors(:,3);
Field21.Wscrit = data(:,6);
Field21.WD = categorical(stringVectors(:,4));
Field21.E = categorical(stringVectors(:,5));
Field21.MOR = stringVectors(:,6);
Field21.Breakingstrain = data(:,7);
Field21.Hmax = data(:,8);
Field21.GrowthRate = data(:,9);
Field21.TreeHeight = data(:,10);
Field21.DBH = data(:,11);
Field21.Volume = data(:,12);
Field21.PathFraction = data(:,13);
Field21.CrownHeight = data(:,14);
Field21.CrownWidth = categorical(stringVectors(:,7));
Field21.CrownAsymmetry = categorical(stringVectors(:,8));
Field21.MeanAngle = data(:,15);
Field21.SailArea = data(:,16);

%% Clear temporary variables
clearvars data raw stringVectors R;